# Generated by Django 6.0.4 on 2026-04-23 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_recurring',
            new_name='close_event_created',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='description',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='close_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='score_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='can_enter_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('positive', 'ئەرێنی'), ('negative', 'نەرێنی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='asset_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenanceasset',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.maintenanceasset'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'نزم'), ('medium', 'مامناوەند'), ('high', 'بەرز'), ('urgent', 'زۆر گرنگ')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'کراوە'), ('in_progress', 'لە جێبەجێکردندایە'), ('done', 'تەواو بووە')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'نزم'), ('medium', 'مامناوەند'), ('high', 'بەرز'), ('urgent', 'زۆر گرنگ')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'لە چاوەڕوانیدا'), ('in_progress', 'لە جێبەجێکردندایە'), ('done', 'تەواو بووە')], default='todo', max_length=20),
        ),
    ]
